name: pokedex
description: A new Flutter project by Marcus Vinicius Correa.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.3
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  flutter_svg: ^1.1.4

flutter_icons:
  android: "launcher_icon"    
  image_path_android: "assets/images/icon.png"  
  image_path_ios: "assets/images/icon.png"

flutter_native_splash:
  color: "#DA0909"
  image: assets/images/logo.png
  android: true  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true
  
  assets:
    - assets/images/